//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoinCableTester.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoinCableTester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Control_Panel {
            get {
                object obj = ResourceManager.GetObject("Control_Panel", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataDownload {
            get {
                object obj = ResourceManager.GetObject("DataDownload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataUpload {
            get {
                object obj = ResourceManager.GetObject("DataUpload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Desktop {
            get {
                object obj = ResourceManager.GetObject("Desktop", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeyEscape {
            get {
                object obj = ResourceManager.GetObject("KeyEscape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeyStart {
            get {
                object obj = ResourceManager.GetObject("KeyStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeyStop {
            get {
                object obj = ResourceManager.GetObject("KeyStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeyTest {
            get {
                object obj = ResourceManager.GetObject("KeyTest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KeyTest2 {
            get {
                object obj = ResourceManager.GetObject("KeyTest2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E,55,20.658,22.9327,A01
        ///C,55,21.674,22.9327,A02
        ///A,55,22.69,22.9327,A03
        ///CB,56,-8.298,23.8141,A04
        ///BY,56,-7.282,23.8141,A05
        ///BV,56,-6.266,23.8141,A06
        ///BT,56,-5.25,23.8141,A07
        ///BP,56,-4.234,23.8141,A08
        ///BM,56,-3.218,23.8141,A09
        ///BK,56,-2.202,23.8141,A10
        ///BH,56,-1.186,23.8141,A11
        ///BF,56,-0.17,23.8141,A12
        ///BD,56,0.846,23.8141,A13
        ///BB,56,1.862,23.8141,A14
        ///AY,56,2.878,23.8141,A15
        ///AV,56,3.894,23.8141,A16
        ///AT,56,4.91,23.8141,A17
        ///AP,56,5.926,23.8141,A18
        ///AM,56,6.942,23.8141,A19
        ///AK,56,7.958,23.8141,A20
        ///AH,56,8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LGA2110_1 {
            get {
                return ResourceManager.GetString("LGA2110_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DF,58,-22.69,24.6629,A01
        ///DD,58,-21.674,24.6629,A02
        ///DB,58,-20.658,24.6629,A03
        ///CY,58,-19.642,24.6629,A04
        ///CV,58,-18.626,24.6629,A05
        ///CT,58,-17.61,24.6629,A06
        ///CP,58,-16.594,24.6629,A07
        ///CM,58,-15.578,24.6629,A08
        ///CK,58,-14.562,24.6629,A09
        ///CH,58,-13.546,24.6629,A10
        ///CF,58,-12.53,24.6629,A11
        ///CD,58,-9.314,25.5769,A12
        ///DE,57,-22.182,23.7815,A13
        ///DC,57,-21.166,23.7815,A14
        ///DA,57,-20.15,23.7815,A15
        ///CW,57,-19.134,23.7815,A16
        ///CU,57,-18.118,23.7815,A17
        ///CR,57,-17.102,23.7815,A18
        ///CN,57,-16.086,23.7815,A19
        ///CL,5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LGA2110_2 {
            get {
                return ResourceManager.GetString("LGA2110_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PointSearchEnd {
            get {
                object obj = ResourceManager.GetObject("PointSearchEnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PointSearchStart {
            get {
                object obj = ResourceManager.GetObject("PointSearchStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReportSearch {
            get {
                object obj = ResourceManager.GetObject("ReportSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StepPlay {
            get {
                object obj = ResourceManager.GetObject("StepPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StepStop {
            get {
                object obj = ResourceManager.GetObject("StepStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TestInfoDialog {
            get {
                return ResourceManager.GetString("TestInfoDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string TestInfoTitle {
            get {
                return ResourceManager.GetString("TestInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zero {
            get {
                object obj = ResourceManager.GetObject("Zero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
